// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CCC_Notes","status":true,"description":"Custom Quest Log for CCC Training Objectives (Auto-Wrap Version).","parameters":{}},
{"name":"CCC_QuizEngine","status":true,"description":"CCC Quiz Engine - Complete 50 MCQ Logic with Auto-Wrap.","parameters":{}},
{"name":"ForceDash","status":true,"description":"Forces dash to always be active.","parameters":{}},
{"name":"NIJI_VideoPlayer","status":true,"description":"v1.3.1 Play videos wherever you want","parameters":{}},
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"false","aGraphic":"WindowArrow","yOffset":"60"}},
{"name":"Gemini_Atmosphere","status":true,"description":"Multi-Cloud Overlay (Map-Specific).","parameters":{}},
{"name":"Gemini_NightSystem","status":true,"description":"Night Environment (Map-Specific).","parameters":{}},
{"name":"Gemini_RainSystem","status":true,"description":"Internal Rain + Lightning Flashes + Thunder SE.","parameters":{}}
];
